# This is a production version of the Bigcapital.

services:
  proxy:
    image: envoyproxy/envoy:v1.30-latest
    depends_on:
      - server
      - webapp
    ports:
      - '${PUBLIC_PROXY_PORT:-80}:80'
      - '${PUBLIC_PROXY_SSL_PORT:-443}:443'
    tty: true
    volumes:
      - ./docker/envoy/envoy.yaml:/etc/envoy/envoy.yaml
    restart: on-failure
    networks:
      - bigcapital_network

  webapp:
    container_name: bigcapital-webapp
    image: bigcapital/webapp:latest
    build:
      context: ./
      dockerfile: packages/webapp/Dockerfile
    restart: on-failure
    networks:
      - bigcapital_network

  server:
    container_name: bigcapital-server
    image: bigcapital/server:latest
    build:
      context: ./
      dockerfile: packages/server/Dockerfile
    ports:
      - "${API_HOST_IP:-0.0.0.0}:${API_PORT:-3000}:3000"
    env_file:
      - .env
    restart: on-failure
    networks:
      - bigcapital_network

  gotenberg:
    image: gotenberg/gotenberg:7
    expose:
      - '9000'
    networks:
      - bigcapital_network

# Networks
networks:
  bigcapital_network:
    driver: bridge
