services:
  server:
    container_name: bigcapital-server
    image: bigcapital/server:latest
    build:
      context: ./
      dockerfile: packages/server/Dockerfile
    ports:
      - "${API_HOST_IP:-0.0.0.0}:${API_PORT:-3000}:3000"
    env_file:
      - .env
    restart: on-failure
    networks:
      - bigcapital_network